import subprocess
from dataclasses import dataclass
from pathlib import Path

from csv_manager import CsvChange


@dataclass
class PullRequest:
    number: int
    url: str
    branch: str


def create_pull_request(
    repo_root: Path,
    issue_numbers: list[int],
    changes: list[CsvChange],
    touched_files: set[Path],
) -> PullRequest:
    branch_suffix = "-".join(str(number) for number in issue_numbers)
    branch = f"jsm-agent/repo-requests-{branch_suffix}"
    title = f"Process repository request{'s' if len(issue_numbers) != 1 else ''}: {', '.join(f'#{n}' for n in issue_numbers)}"
    body = build_pr_body(issue_numbers, changes)

    _run(["git", "config", "user.name", "github-provisioning-agent"], repo_root)
    _run(["git", "config", "user.email", "github-provisioning-agent@users.noreply.github.com"], repo_root)
    _run(["git", "checkout", "-B", branch], repo_root)

    paths = sorted(str(path.relative_to(repo_root)) for path in touched_files)
    _run(["git", "add", *paths], repo_root)
    _run(["git", "commit", "-m", title], repo_root)
    _run(["git", "push", "--force-with-lease", "--set-upstream", "origin", branch], repo_root)

    pr_url = _run_with_output(
        [
            "gh",
            "pr",
            "create",
            "--title",
            title,
            "--body",
            body,
            "--head",
            branch,
        ],
        repo_root,
    )
    pr_number = int(pr_url.rstrip("/").split("/")[-1])
    return PullRequest(number=pr_number, url=pr_url, branch=branch)


def build_pr_body(issue_numbers: list[int], changes: list[CsvChange]) -> str:
    created = [change for change in changes if change.action == "created"]
    updated = [change for change in changes if change.action == "updated"]
    skipped = [change for change in changes if change.action == "skipped"]

    lines = [
        "## Summary",
        "",
        f"- Processed repository request issue(s): {', '.join(f'#{number}' for number in issue_numbers)}",
        f"- Created rows: {len(created)}",
        f"- Updated rows: {len(updated)}",
        f"- Already correct rows: {len(skipped)}",
        "",
        "## CSV Changes",
        "",
    ]

    for change in changes:
        lines.append(f"- `{change.file}` `{change.key}`: **{change.action}** - {change.details}")

    lines.extend(
        [
            "",
            "## Reviewer Checklist",
            "",
            "- Confirm the request fields match the CSV changes.",
            "- Run or review the `deploy-github` Terraform plan after merge.",
            "- For `iac_setup=true`, confirm AWS OIDC role and state bucket secrets are configured.",
            "",
            "## Agent Notes",
            "",
            "This PR was generated by the repository request agent from structured GitHub Issue Form input.",
        ]
    )
    return "\n".join(lines)


def _run(command: list[str], cwd: Path) -> None:
    subprocess.run(command, cwd=cwd, check=True)


def _run_with_output(command: list[str], cwd: Path) -> str:
    completed = subprocess.run(command, cwd=cwd, check=True, capture_output=True, text=True)
    return completed.stdout.strip()
