import os
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

import requests

from csv_manager import CsvChange


@dataclass
class PullRequest:
    number: int
    url: str
    branch: str


def create_pull_request(
    repo_root: Path,
    issue_numbers: list[int],
    changes: list[CsvChange],
    touched_files: set[Path],
) -> PullRequest:
    branch = f"jsm-agent/repo-requests-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}"
    title = f"Process repository request{'s' if len(issue_numbers) != 1 else ''}: {', '.join(f'#{n}' for n in issue_numbers)}"
    body = build_pr_body(issue_numbers, changes)

    _run(["git", "checkout", "-b", branch], repo_root)
    _run(["git", "config", "user.name", "github-provisioning-agent"], repo_root)
    _run(["git", "config", "user.email", "github-provisioning-agent@users.noreply.github.com"], repo_root)

    paths = sorted(str(path.relative_to(repo_root)) for path in touched_files)
    _run(["git", "add", *paths], repo_root)
    _run(["git", "commit", "-m", title], repo_root)
    _run(["git", "push", "--set-upstream", "origin", branch], repo_root)

    github_repository = os.environ["GITHUB_REPOSITORY"]
    token = os.environ["GITHUB_TOKEN"]
    default_branch = os.environ.get("DEFAULT_BRANCH", "main")

    response = requests.post(
        f"https://api.github.com/repos/{github_repository}/pulls",
        headers=_headers(token),
        json={
            "title": title,
            "head": branch,
            "base": default_branch,
            "body": body,
        },
        timeout=30,
    )
    response.raise_for_status()
    payload = response.json()
    return PullRequest(number=payload["number"], url=payload["html_url"], branch=branch)


def build_pr_body(issue_numbers: list[int], changes: list[CsvChange]) -> str:
    created = [change for change in changes if change.action == "created"]
    updated = [change for change in changes if change.action == "updated"]
    skipped = [change for change in changes if change.action == "skipped"]

    lines = [
        "## Summary",
        "",
        f"- Processed repository request issue(s): {', '.join(f'#{number}' for number in issue_numbers)}",
        f"- Created rows: {len(created)}",
        f"- Updated rows: {len(updated)}",
        f"- Already correct rows: {len(skipped)}",
        "",
        "## CSV Changes",
        "",
    ]

    for change in changes:
        lines.append(f"- `{change.file}` `{change.key}`: **{change.action}** - {change.details}")

    lines.extend(
        [
            "",
            "## Reviewer Checklist",
            "",
            "- Confirm the request fields match the CSV changes.",
            "- Run or review the `deploy-github` Terraform plan after merge.",
            "- For `iac_setup=true`, confirm AWS OIDC role and state bucket secrets are configured.",
            "",
            "## Agent Notes",
            "",
            "This PR was generated by the repository request agent from structured GitHub Issue Form input.",
        ]
    )
    return "\n".join(lines)


def _headers(token: str) -> dict[str, str]:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _run(command: list[str], cwd: Path) -> None:
    subprocess.run(command, cwd=cwd, check=True)
